// import { da, el } from 'date-fns/locale'
import { NextRequest, NextResponse } from 'next/server'
import { GoogleSpreadsheet } from 'google-spreadsheet'
import { JWT } from 'google-auth-library'
import { func } from 'prop-types'

export async function POST(request) {
  const greeting = 'Hello World!!'
  const json = {
    greeting,
  }

  async function getNIUfromSHEET(sheet, val) {
    const rows = await sheet.getRows()
    var result = true
    for (const obj of rows) {
      const rawData = obj._rawData

      if (rawData[1] == val) {
        result = false
      }
    }
    return result
  }

  async function getDataNiu(niu) {
    try {
      const response = await fetch(`https://kpum.wg.ugm.ac.id/2020/cek-dpt/cekniu.php?niu=${niu}`)

      const data = await response.json()
      if (data.nama && data.fakultas_nama) {
        var jsonString = JSON.stringify({
          niu: data.niu,
          nama: data.nama,
          fakultas: niuData.fakultas_nama,
        })

        return data
      } else {
        return false
      }
    } catch (error) {
      console.log(error)
    }
  }

  async function insertToSheet(sheet, niuData) {
    console.log(niuData)
    try {
      const rowData = {
        timestamp: 'timestamp',
        niu: niuData.niu,
        nama: niuData.nama,
        fakultas: niuData.fakultas_nama,
        // Add more columns as needed
      }
      const addedRow = await sheet.addRow(rowData)

      // Check if the row was added successfully
      if (addedRow !== null) {
        console.log('Row added successfully')
        return true
      } else {
        console.error('Error adding row to the spreadsheet.')
        return false
      }
    } catch (error) {
      return false
    }
  }

  try {
    const serviceAccountAuth = new JWT({
      // env var values here are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      email: 'gelex-2024@abiding-ion-432720-a4.iam.gserviceaccount.com',
      key: '-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCbUTcmI+d9RcYT\ns0bPud78wpGPDmmYfrRSYI1U2um2ZWspswASTEWlGrs3QacFCHSP2IDBr9gZwIqG\nQF4JdrBH075Xl7TRB9yG7yyHMmm8ju+4d0Zk074+NxJ5TeQxwTtmI1pGltg7OnYI\nKZ6fp/5Pi0HtGbXI1BWq87rpOWKqyEZTDKlGL89I66oJS29n3fSxvpGU9znV1XLH\n5M44ty/MOb9QD1YPgBW6PqX0MAnfCtV0lwgKRua0KuRbWn8eKF0OZ7X0ZgPcniqQ\nCS5ctKJdZLkqFl5De2AkY63TfXXRnvMF/UvVTGLqMpTG6bRuE3qMA/sKu9h4fltQ\nKgUgU6xNAgMBAAECggEAELenJfXLXtJ5xXkQcB9jfvU6UZmNiBprMkquK6n8aeN0\nq2JW6aFIBcNgz0vDvGjykuEMyswwiGUPA/A9rusVgkWqQSdVEQK1m9h2hH7Knr8L\n0mEUNJoN6ghndqMJoslXqWC4wMxPreBW//3q0uh0GP+2Mt0Hkfwx8NqXDa9djWAi\nNGXn6yF1yTWCARSzOkZ3asjHUMMRqSP9Kiij2mFxfV9IL0CagLaiJPNBkX0TNA5N\nXAv5SnkieKT1oUPf7gvIj+zdBBpTSghV6mfcQXUErfBnmlbaj8XwU6xYtCzwylu+\n7gqITaJ9kMcrAoc1NUPFc40CCwm2bgGyYN9uatqzQQKBgQDI5ofiquswwUMeI9LE\nMHzmrqw1BLLA0EaZ+DR02Phr8QIBR7dEvcNFsUrGuMw44j9K9JPPcEz80TQVoMHM\n5PY7IJUwZLhgiA/eONUkE4SafeCclc01ilN75oAYQf2STyFTiXWo9xjVTc7cnlEp\nspeCJC3st50YiTI/LH8mk+gjNQKBgQDF6jpwfEw1Cun45QKjRPaWNGvHtm6gyiAT\nBHa3xHF4DNYiZTi4gKhQKLFwlq0HBU4jkJXva/F1sHePSIOakHNvYrOjyxM0HskX\nnle6G0TbauiVQfXNGdFxERS1jvjZcjZx6X8PFUNVKv0FsCxB/LNl0AxvcGFBSaiR\nDLz33p2vuQKBgQCguL0RO4e4k4RsgmBFkDz8F9Ww/Lc8xeMVnpnouQPU5xShjYwy\ntFWaVcHqxUCsaWQVRSFTHRaaU4uFmfwxPSM4HlL8SjevEmsPbwwlNnApYHbnDnkD\nUkyDnN3xiimgeSnCOQAmUrhNPVg263knELdg6CzNaf+F94x5OdHnPQDD2QKBgQCQ\nqLl6Sn/xLT8C+3DIIboS49H7sa5+u/5hqBuWCnHdi5Rgo5en0/IyVOwNHTTvMsOA\nX0gYLc/Zc9iP1DLNINQfEAe5qs8og2/8YXJBx3i24BeMMSAWf86EVDXM1umxFjgR\nXtfOEH6cm8VBCRnwSWJfAoh0U7HiZJJfIu5kRkT/kQKBgQCEosw+Ogt9JOz0B2No\nVTBsoWIbM4P5xW9Utbeore2ZxJ7ljvZFr8EgVSwfgL4zJyRHRag8fpRBMs+AcZON\nhpZebH5aB1ggmDj4fbxG+kkDE4vUXvZH5QW7+BtfCC9jnBNWs2IH4sixdfNbxP63\n3FJVvYDcKeS00EfZsH2oz04mpQ==\n-----END PRIVATE KEY-----\n',
      scopes: ['https://www.googleapis.com/auth/spreadsheets'],
    })

    // Add your Google Sheets credentials
    const spreadsheetId = '1aIjg4TTfhS2zVgrtg2tZEoF8rtOwOq9wgl8FU0BZMqU'

    // Replace 'YOUR_GOOGLE_SERVICE_ACCOUNT_EMAIL' and 'YOUR_PRIVATE_KEY' with your Google Service Account credentials

    const doc = new GoogleSpreadsheet(spreadsheetId, serviceAccountAuth)

    await doc.loadInfo() // loads document properties and worksheets
    console.log(doc.title)
    await doc.use
    await doc.loadInfo() // loads document properties and worksheets

    // Replace 'Sheet1' with the name of the sheet in your spreadsheet
    const sheet = doc.sheetsByTitle['Sheet1']

    // console.log(request)
    const niu = '505121'
    const niuData = await getDataNiu(niu)

    if (niuData) {
      const niuAvailability = await getNIUfromSHEET(sheet, niu)
      if (niuAvailability) {
        const insertSuccess = await insertToSheet(sheet, niuData)
        if (insertSuccess) {
          return NextResponse.json(
            {
              message: 'Data Inserted to sheet succesfully!',
              data: {
                niu: niuData.niu,
                nama: niuData.nama,
                prodi: niuData.prodi_nama,
              },
            },
            {
              status: 201,
            },
          )
        }
      } else {
        return NextResponse.json(
          { message: 'NIU was inserted to SHEET!' },
          {
            status: 404,
          },
        )
      }
    } else {
      return NextResponse.json(
        { message: 'NIU Not Found' },
        {
          status: 404,
        },
      )
    }
  } catch (error) {
    console.log(error)
    return NextResponse.json(
      { message: error },
      {
        status: 500,
      },
    )
  }
}
